{
  "uid" : "46808f6c691c922d",
  "name" : "test_xfail_unexpected_pass___",
  "fullName" : "vkr_project_tests.test_attach#test_xfail_unexpected_pass___",
  "historyId" : "49075655edb191ab4db2f61f5fb1b8be",
  "time" : {
    "start" : 1649447324177,
    "stop" : 1649447324177,
    "duration" : 0
  },
  "description" : "this test is an xfail that will be marked as unexpected success",
  "descriptionHtml" : "<p>this test is an xfail that will be marked as unexpected success</p>\n",
  "status" : "passed",
  "statusMessage" : "XPASS this test is expecting failure",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "tag",
    "value" : "@pytest.mark.xfail(condition=<function <lambda> at 0x7ff0d5ec4700>, reason='this test is expecting failure')"
  }, {
    "name" : "parentSuite",
    "value" : "vkr_project_tests"
  }, {
    "name" : "suite",
    "value" : "test_attach"
  }, {
    "name" : "host",
    "value" : "fv-az135-297"
  }, {
    "name" : "thread",
    "value" : "2334-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "vkr_project_tests.test_attach"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ ],
    "tags" : [ "@pytest.mark.xfail(condition=<function <lambda> at 0x7ff0d5ec4700>, reason='this test is expecting failure')" ]
  },
  "source" : "46808f6c691c922d.json",
  "parameterValues" : [ ]
}